version: '3.8'

services:
  mywebclient:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5001:5001"
    environment:
      NODE_ENV: production
    volumes:
      - /home/ubuntu/data:/data
    restart: always
